apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: myjob
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: cgr.dev/zachary.yonash/imagemagick:7@sha256:602c411cbe4a4a0a5c290795f5dc4b94f63108774cf19556513a35786cf65b07
