apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: myjob
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: cgr.dev/zachary.yonash/imagemagick:7@sha256:d262350484e4db0d8713ea690b08a7cf7fc11eaef7f1acc7ad57d2f11aa33a82
