apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: myjob
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: cgr.dev/zachary.yonash/imagemagick:7@sha256:eaef1860d4aa9a45a0b520479b44c4e13af8e223aff08823a5e29e7144e4b92a
