name: Digestabot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  digestabot:
    name: Digestabot
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - uses: chainguard-dev/setup-chainctl
      with: 
        identity: ${{ secrets.CHAINCTL_IDENTITY }} 

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    # Run digestabot
    - uses: chainguard-dev/digestabot@a3b776c1ca57d3127c85578cde8fef6eed3c75d3 # v1.2.3
      id: digestabot
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title-for-pr: 'Update Digests'
        commit-message: 'Update Digests'
        branch-for-pr: digestabot
        labels-for-pr: ''
